# -*- coding: utf-8 -*-
"""pull_data_and_convert_raw_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FSKzkQnNIlFnPGyrVML_O20lsfKRZD7B

<H4>Import Libraries
"""

import pandas as pd
import pyrebase

"""<H4>Firebase Config"""

config = {
    "apiKey": "MHiq73lcNJ7G2V2eg8eAmuzLYAqPMg4dVvwUT2Hw",
    "authDomain": "https://nodemcu-test2-default-rtdb.europe-west1.firebaseapp.com",
    "databaseURL": "https://nodemcu-test2-default-rtdb.europe-west1.firebasedatabase.app/",
    "storageBucket": "https://nodemcu-test2-default-rtdb.europe-west1.appspot.com"
}

"""<h4>Pull Data From Firebase"""

firebase = pyrebase.initialize_app(config)
db = firebase.database()

data = db.get()
val=data.val()
floors = []
for i in data.each():
    floors.append(i.key())
floorids = []
wifiData = {}
for i in floors:
    floorids.append(val[i].keys())
for i,j in zip(floors,floorids):
    wifiData.update({i:val[i][list(j)[0]]})

"""Convert json data to csv data"""

address = []
channel = []
signal = []
ssid = []
timestamp = []
arucoId = []
quality = []
measureId = []
xzemin = [4, 2, 0, -2, -4, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6,-6,-6]
xldata = [0, -2, -4, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6,-6,-6]
xldatanew = []
yldatanew = []
yrdatanew = []
xrdatanew = []
xzeminnew = []
yldata = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46,48,50]
xrdata = [0, 2, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,6,6]
yrdata = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46,48,50]
zdata = [0.0,4.0,8.0,12.0]
for i,j,k,l,m in zip(xldata,xrdata,yldata,yrdata,xzemin):
    xldatanew.append(i/1.6667)
    xrdatanew.append(j/1.6667)
    yldatanew.append(k/1.6667)
    yrdatanew.append(l/1.6667)
    xzeminnew.append(m/1.6667)
xldata=xldatanew
yldata=yldatanew
xrdata=xrdatanew
yrdata=yrdatanew
xzemin=xzeminnew
x=[]
y=[]
z=[]

for i in wifiData:
    for j in range(len(wifiData[i])):
        for k in wifiData[i][j]:
            if(int(wifiData[i][j][k]['id'])<50):
                x.append(xzeminnew[int(wifiData[i][j][k]['id'])])
                y.append(yldata[int(wifiData[i][j][k]['id'])])
                z.append(zdata[0])
            elif(int(wifiData[i][j][k]['id'])>=50 and int(wifiData[i][j][k]['id'])<100):
                x.append(xzeminnew[int(wifiData[i][j][k]['id'])-50])
                y.append(yrdata[int(wifiData[i][j][k]['id'])-50])
                z.append(zdata[0])
            elif(int(wifiData[i][j][k]['id'])>=100 and int(wifiData[i][j][k]['id'])<150):
                x.append(xldata[int(wifiData[i][j][k]['id'])-100])
                y.append(yldata[int(wifiData[i][j][k]['id'])-100])
                z.append(zdata[1])
            elif(int(wifiData[i][j][k]['id'])>=150 and int(wifiData[i][j][k]['id'])<200):
                x.append(xrdata[int(wifiData[i][j][k]['id'])-150])
                y.append(yrdata[int(wifiData[i][j][k]['id'])-150])
                z.append(zdata[1])
            elif(int(wifiData[i][j][k]['id'])>=200 and int(wifiData[i][j][k]['id'])<250):
                x.append(xldata[int(wifiData[i][j][k]['id'])-200])
                y.append(yldata[int(wifiData[i][j][k]['id'])-200])
                z.append(zdata[2])
            elif(int(wifiData[i][j][k]['id'])>=250 and int(wifiData[i][j][k]['id'])<300):
                x.append(xrdata[int(wifiData[i][j][k]['id'])-250])
                y.append(yrdata[int(wifiData[i][j][k]['id'])-250])
                z.append(zdata[2])
            elif(int(wifiData[i][j][k]['id'])>=300 and int(wifiData[i][j][k]['id'])<350):
                x.append(xldata[int(wifiData[i][j][k]['id'])-300])
                y.append(yldata[int(wifiData[i][j][k]['id'])-300])
                z.append(zdata[3])
            elif(int(wifiData[i][j][k]['id'])>=350 and int(wifiData[i][j][k]['id'])<380):
                x.append(xrdata[int(wifiData[i][j][k]['id'])-350])
                y.append(yrdata[int(wifiData[i][j][k]['id'])-350])
                z.append(zdata[3])
            else:
                continue
            measureId.append(j)
            address.append(wifiData[i][j][k]['address'])
            channel.append(wifiData[i][j][k]['channel'])
            signal.append(wifiData[i][j][k]['signal'])
            ssid.append(['ssid'])
            timestamp.append(wifiData[i][j][k]['time'])
            arucoId.append(wifiData[i][j][k]['id'])
            quality.append(wifiData[i][j][k]['quality'])



df=pd.DataFrame({
    'address':address,
    'channel':channel,
    'signal':signal,
    'timestamp':timestamp,
    'arucoId':arucoId,
    'quality':quality,
    'x':x,
    'y':y,
    'z':z,
    'measure ID':measureId
})

"""<h4>Show First 10 Rows"""

df.head(10)

"""<h4>Save dataframe as raw_data.csv"""

df.to_csv("raw_data.csv")